AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"
Description: Cloud Computing Assignment 2 Smart Photo Album
Resources:
  spamDetectorLambda:
    Type: "AWS::Serverless::Function"
    Properties:
      FunctionName: spamDetectorLambda
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      CodeUri: ./
      Description: ""
      MemorySize: 128
      Timeout: 183
      Role: "arn:aws:iam::877755470769:role/admin-role-lambda"
      Events:
        S3Trigger:
          Type: S3
          Properties:
            Bucket: !Ref s3BucketEmailStorage
            Events: s3:ObjectCreated: "*"
      Environment:
        Variables:
          REGION: us-west-2
          ENDPOINT: sms-spam-classifier-mxnet-2021-12-02-05-57-55-675
      Layers:
        - arn:aws:lambda:us-west-2:420165488524:layer:AWSLambda-Python36-SciPy1x:35

  s3SpamPipeline:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: s3SpamPipeline
      PublicAccessBlockConfiguration:
        BlockPublicAcls: False
        BlockPublicPolicy: False
        IgnorePublicAcls: False
        RestrictPublicBuckets: False

  s3SpamPipelinePolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref s3SpamPipeline
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
              - s3:*
            Effect: Allow
            Resource: !Join
              - ''
              - - 'arn:aws:s3:::'
                - !Ref s3SpamPipeline
                - /*
            Principal: '*'

